library(dplyr)
library(Matrix)
library(future)
library(foreach)
plan("multisession", cores = 8)
library(partitions)
library(MASS)
library(matrixcalc)
library(tidyverse)
library(ggplot2)
library(reshape2)
library(readxl)
library(readr)
